name: Run Assessment Unit Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # adjust if needed

      - name: Run unit tests
        run: python3 -m pytest assessemts/tests.py

